spring.application.name=cbs-harita-app
map.data.path=C:/Users/Milsoft/Desktop/geojson veri
server.port=8080

# PostgreSQL Veritabanı Bağlantı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/cbs_harita
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA ve Hibernate Ayarları
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Veritabanı tablolarını Java koduna göre otomatik oluştur/güncelle
spring.jpa.hibernate.ddl-auto=update

# Hibernate 6 (Spring Boot 3) bunu otomatik algılayacak. Dialect Hibernate'e harita diliyle konuşmasını söyleyecek